services:
  postgres:
    image: postgres:17
    container_name: mock_trader_db
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: mock_trader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  pgdata:
